/**
 * Lista de bancos colombianos vigentes (Superintendencia Financiera).
 * Ordenada alfabeticamente para que el desplegable sea predecible.
 */
export const BANCOS_COLOMBIA: string[] = [
  'AV Villas',
  'Banco Agrario de Colombia',
  'Banco Caja Social',
  'Banco Cooperativo Coopcentral',
  'Banco Davivienda',
  'Banco de Bogota',
  'Banco de Occidente',
  'Banco Falabella',
  'Banco Finandina',
  'Banco GNB Sudameris',
  'Banco ITAU',
  'Banco Pichincha',
  'Banco Popular',
  'Banco Santander Colombia',
  'Banco Serfinanza',
  'Banco W',
  'BancoOmnia',
  'Bancolombia',
  'BBVA Colombia',
  'BTG Pactual',
  'CFA Cooperativa Financiera de Antioquia',
  'Citibank Colombia',
  'Coltefinanciera',
  'Cooperativa Financiera Confiar',
  'Daviplata',
  'JP Morgan Colombia',
  'Lulo Bank',
  'Mibanco',
  'Movii',
  'Nequi',
  'Nu Bank',
  'Powwi',
  'RappiPay',
  'Scotiabank Colpatria',
];
